
# Control the number of replicas for the chat-service
replicaCount: 1

# Base informations for the service image
image:
  repository: positionpal/user-service
  tag: 1.4.1@sha256:5d4f0dce7fabac4fcc57c2cbcb99c561482386c9607e266e6f46e83bd03e3d35
  pullPolicy: IfNotPresent

jwtSecret: "abc"

# Configure the service type and the port it exposes
service:
  type: ClusterIP
  port: 5052

# Configure the connection information for the rabbtimq service
rabbitmq:
  username: user
  password: XkdcPscPihKNZDYQ
  namespace: rabbitmq
  serviceName: rabbitmq
  port: 5672

# Configure the connection information for the postgresql service
# see https://artifacthub.io/packages/helm/bitnami/postgresql for more information about the configuration
postgresql:
  enabled: true
  port: 5432
  
  global:
    postgresql:
      auth:
        username: user
        password: password
        postgresPassword: password
        database: users_and_groups

  primary:
    initdb:
      scriptsConfigMap: script-db-configmap