apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-user-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5052
  selector:
  {{- include "user-service.labels" . | nindent  4}}