apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-user-service-secrets
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.global.postgresql.auth.password | b64enc }}
  rabbitmq-password: {{ .Values.rabbitmq.password | b64enc }}
  jwt-secret: {{ .Values.jwtSecret | b64enc }}